### PR TITLE
Adding the 'MotorRecord' PVGroup to simulate a motor axis

### PR DESCRIPTION
**Pull request by awalter-bnl**
This PR adds a 'MotorRecord' PVGroup which simulates the PVs, and the set functionality, of an Epics Motor record based motion axis. I think I have included all of the required PVs but future PRs can add more as required.

@Jiemin-Li and @wen-hu please review this, for all others I welcome comments/suggestions.

### CODE REVIEW

**Review by Jiemin-Li — COMMENTED** [review]
Not sure whether we should wrap up the user_limits in MotorRecord. But if it's consistent with the logic in EPICS, we can keep it here.

**Comment by awalter-bnl** [comment]
> Not sure whether we should wrap up the user_limits in MotorRecord. But if it's consistent with the logic in EPICS, we can keep it here.

Thanks for the review @Jiemin-Li, This is an interesting comment. The user_limits PV's (suffix.HLS and suffix.LLS) are both part of the EPICS motor record set of PVs, so I think they need to stay. Did you mean that you are not sure we should implement the functionality of tripping these limits when moving the motor?

**Review by Jiemin-Li — COMMENTED** [review]
Should we also add user_offset (it's called as calibration in CSS) and backlash for this Motor Record?

**Comment by Jiemin-Li** [comment]
> stay

**Comment by Jiemin-Li** [comment]
> > Not sure whether we should wrap up the user_limits in MotorRecord. But if it's consistent with the logic in EPICS, we can keep it here.
> 
> Thanks for the review @Jiemin-Li, This is an interesting comment. The user_limits PV's (suffix.HLS and suffix.LLS) are both part of the EPICS motor record set of PVs, so I think they need to stay. Did you mean that you are not sure we should implement the functionality of tripping these limits when moving the motor?

I was thinking whether the user_limits is the attribute of motor, or it should belong to the Motor Record. If this is in line with EPICS motor record set, we should put it here.

**Comment by awalter-bnl** [comment]
> Should we also add user_offset (it's called as calibration in CSS) and backlash for this Motor Record?

@Jiemin-Li These are likely motor record PVs so I am happy to add them. Can I ask you to take a look at our test bench and let me know what the PV's are for these so I can add them correctly?

**Comment by awalter-bnl** [comment]
@Jiemin-Li I have added the requested user_offset and backlash PVs !-).

**Comment by awalter-bnl** [comment]
@wen-hu please take a look and merge when you are OK with it.

**Comment by awalter-bnl** [comment]
@Jiemin-Li and @wen-hu , 
Jiemin sorry for making changes after your review, I found some required changes as the original submission did not work. Most notably I needed to use:
`self.user_readback.write(..)` 
instead of 
`self.user_readback = ...` 
and 
`self.user_readback.value` 
instead of 
`...= self.user_readback`
for all pvproperty objects.

**Comment by awalter-bnl** [comment]
Closing this Pull Request as I will take a very different approach to the MotorRecord PVGroup. I will open a new PR when this is ready.

**Pull request closed without merging**
