### PR TITLE
Adding a QuadEM PVGroup and using this in the BaffleSlit PVGroup

### PR DESCRIPTION
**Pull request by awalter-bnl**
This PR aims to add a QuadEM PVGroup, to simulate the PVs from an NSLS-II standard quad electrometer, and to use this as a subgroup inside the BaffleSlit IOC server.

As the quad EMs have areadetector based IOCs this unfortunately meant I had to implement a bunch of PVs. To do this I have added an 'areadetector' sub-package containing plugin_base, stats_plugin and quad_em modules. This will allow for the re-use of much of the code for these in future areadetector IOCs. Some notes on connections between the various PVs in the QuadEM PVGroup are given below.

    NOTES:
    1. Unless otherwise listed below the PVs generated in this PR are 'Dummy' PVs
    that are not modified by any inputs, or modify any other PVs, except there own
    values when they are updated.
    2. In QuadEM when self.acquire is set to 1 the sequence of events is:
        i. record the initial time and set self.num_averaged to 0.
        ii.  calculate the current to be set on each channel using self._generate_current 
        and write these to the self.current(x).mean_value attributes (x in [1,2,3,4])
        iii. if self.averaging_time has elapsed continue otherwise wait until it has.
        iv. set self.num_averaged to self.num_average and self.acquire to 0
    3. In QuadEM when self.averaging_time or self.integrating_time are updated self.num_average is
    updated using the following relationship:
        - self.num_average = floor(self.averaging_time/self.integration_time)

### CODE REVIEW

**Comment by awalter-bnl** [comment]
@Jiemin-Li and @wen-hu please review this at your convenience. Comments/suggestions from others are strongly encouraged as well !-).

**Comment by awalter-bnl** [comment]
Sorry for the bunch of new commits. I noticed an issue whereby there was a 'Caproto_servers' directory and and a 'caproto_servers' directory. The new commits resolve that and merge them.

**Review by Jiemin-Li — COMMENTED** [review]
Two quick comments:
1) The area_detector.plugin_base and area_detector.stats_plugin come from the Ophyd package, right? If so, should we add 'ophyd.' to the front of these two imports?
2) In the function of _reset_num_average(self), there is no argument after 'return', is it following the python syntax?

**Comment by awalter-bnl** [comment]
@Jiemin-Li thanks for the comments, I respond below.
> Two quick comments:
> 
>     1. The area_detector.plugin_base and area_detector.stats_plugin come from the Ophyd package, right? If so, should we add 'ophyd.' to the front of these two imports?

Yes and no, there are class objects within ophyd with the same names but they are not the same as the ones in this PR. The items in ophyd are for creating 'ophyd objects' that talk to a bunch of PVs. I created new objects in this package that create the PVs that those ophyd objects will talk to and used the same names. So long story short, the references here are for the objects from this package which have the same name as the objects in ophyd. This package will be run in a different python session than the ophyd objects so it is not necessary (and not advised) to reference ophyd in this package !-).


>     2. In the function of _reset_num_average(self), there is no argument after 'return', is it following the python syntax?

A quick google search showed this statement on python return usage:

_You can use explicit return statements with or without a return value. If you build a return statement without specifying a return value, then you'll be implicitly returning None_ 

So in this case it is fine, although not strictly required as I do not use:
`some_object=_reset_num_average(self)`
On the off chance that we do use it in that way later I would prefer to keep the 'return' at the end, is this ok with you @Jiemin-Li ?

**Comment by Jiemin-Li** [comment]
> @Jiemin-Li thanks for the comments, I respond below.
> 
> > Two quick comments:
> > ```
> > 1. The area_detector.plugin_base and area_detector.stats_plugin come from the Ophyd package, right? If so, should we add 'ophyd.' to the front of these two imports?
> > ```
> 
> Yes and no, there are class objects within ophyd with the same names but they are not the same as the ones in this PR. The items in ophyd are for creating 'ophyd objects' that talk to a bunch of PVs. I created new objects in this package that create the PVs that those ophyd objects will talk to and used the same names. So long story short, the references here are for the objects from this package which have the same name as the objects in ophyd. This package will be run in a different python session than the ophyd objects so it is not necessary (and not advised) to reference ophyd in this package !-).
> 
> > ```
> > 2. In the function of _reset_num_average(self), there is no argument after 'return', is it following the python syntax?
> > ```
> 
> A quick google search showed this statement on python return usage:
> 
> _You can use explicit return statements with or without a return value. If you build a return statement without specifying a return value, then you'll be implicitly returning None_
> 
> So in this case it is fine, although not strictly required as I do not use: `some_object=_reset_num_average(self)` On the off chance that we do use it in that way later I would prefer to keep the 'return' at the end, is this ok with you @Jiemin-Li ?

These are clear, thanks for the explanation @awalter-bnl.

**Comment by awalter-bnl** [comment]
@wen-hu please take a look at this when you get a chance.

**Pull request merged**
